In [1]:
import numpy as np
x = np.array([1,2,3])

In [2]:
print(x)

[1 2 3]


In [3]:
print(x.reshape((3,1)))

[[1]
 [2]
 [3]]


In [4]:
A = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.arange(12).reshape((3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
t = np.arange(36).reshape((3,3,4))
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [11]:
print(t[0])
print(t[0,1])
print(t[0,1,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6


In [12]:
t = np.array([[1,2,3], [4,5,6]])
print(t)

[[1 2 3]
 [4 5 6]]


In [14]:
w = t[np.newaxis,:,:]
w.shape

(1, 2, 3)

In [15]:
print(w)

[[[1 2 3]
  [4 5 6]]]


## 브로드캐스팅 규칙

In [19]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7 ,8, 9], [10, 11, 12]])
c = np.array([10,100,100])
d = np.array([10, 11])

print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[ 10 100 100]
[10 11]


In [20]:
print(a+b)
print(a-b)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [21]:
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [23]:
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [25]:
print(b**a)

[[      7      64     729]
 [  10000  161051 2985984]]


In [26]:
print(a+c)

[[ 11 102 103]
 [ 14 105 106]]


In [27]:
print(c*a)

[[ 10 200 300]
 [ 40 500 600]]


In [28]:
print(a/c)

[[0.1  0.02 0.03]
 [0.4  0.05 0.06]]


In [29]:
d = d.reshape((2,1))

In [31]:
d.shape

(2, 1)

단위벡터

In [33]:
v = np.array((2, -4, 3))
u = v / np.sqrt((v*v).sum())
print(u)

[ 0.37139068 -0.74278135  0.55708601]


In [38]:
v_1 = np.array([1, 2, 3])
v_1 = v_1.reshape((1,3))

print(v_1.transpose())

[[1]
 [2]
 [3]]


In [40]:
print(v_1.T)

[[1]
 [2]
 [3]]


In [41]:
a= np.array([1,2,3,4])
b = np.array([5,6,7,8])
def inner(a,b):
    s = 0.0
    for i in range(len(a)):
        s += a[i] *b[i]
    return s

inner(a,b)

70.0

In [42]:
(a*b).sum()

70

In [43]:
np.dot(a,b)

70

In [45]:
A = np.sqrt(np.dot(a,a))
B = np.sqrt(np.dot(b,b))
t = np.arccos(np.dot(a,b)/(A*B))
t*(180/np.pi)

14.335170291600924

In [46]:
a = np.array([1,0,0])
b = np.array([0,1,0])
np.dot(a,b)

0

In [47]:
a =np.array([1,1])
b = np.array([1,0])
p = (np.dot(a,b)/np.dot(b,b))*b
print(p)

[1. 0.]


In [49]:
c = np.array([[-1,1]])
p = (np.dot(c,b)/np.dot(b,b))*b
print(p)

[-1. -0.]
